<?php

namespace App\Form;

use App\Entity\Pass;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class PassFormType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('periode')
            ->add('date')
            ->add('abo_fitness')
            ->add('desabo_fitness')
            ->add('inst_fitness')
            ->add('abo_fitness_hc')
            ->add('desabo_fitness_hc')
            ->add('inst_fitness_hc')
            ->add('abo_fitness_matin')
            ->add('desabo_fitness_matin')
            ->add('inst_fitness_matin')
            ->add('abo_aquatic')
            ->add('desabo_aquatic')
            ->add('inst_aquatic')
            ->add('abo_aquatic_hc')
            ->add('desabo_aquatic_hc')
            ->add('inst_aquatic_hc')
            ->add('abo_aquatic_plus')
            ->add('desabo_aquatic_plus')
            ->add('inst_aquatic_plus')
            ->add('abo_aquaform')
            ->add('desabo_aquaform')
            ->add('inst_aquaform')
            ->add('abo_aquaform_plus')
            ->add('desabo_aquaform_plus')
            ->add('inst_aquaform_plus')
            ->add('abo_aquaform_hc')
            ->add('desabo_aquaform_hc')
            ->add('inst_aquaform_hc')
            ->add('abo_aquaform_plus_hc')
            ->add('desabo_aquaform_plus_hc')
            ->add('inst_aquaform_plus_hc')
            ->add('abo_forme')
            ->add('desabo_forme')
            ->add('inst_forme')
            ->add('abo_forme_eau')
            ->add('desabo_forme_eau')
            ->add('inst_forme_eau')
            ->add('abo_aquabalneo')
            ->add('desabo_aquabalneo')
            ->add('inst_aquabalneo')
            ->add('abo_balneo_fitness')
            ->add('desabo_balneo_fitness')
            ->add('inst_balneo_fitness')
            ->add('abo_top_forme_balneo')
            ->add('desabo_top_forme_balneo')
            ->add('inst_top_forme_balneo')
            ->add('abo_top_forme_fitness')
            ->add('desabo_top_forme_fitness')
            ->add('inst_top_forme_fitness')
            ->add('abo_top_vitalite_fitbain')
            ->add('desabo_top_vitalite_fitbain')
            ->add('inst_top_vitalite_fitbain')
            ->add('abo_tonicite')
            ->add('inst_desabo_tonicite')
            ->add('abo_promo')
            ->add('desabo_promo')
            ->add('inst_promo')
            ->add('abo_hc')
            ->add('desabo_hc')
            ->add('inst_hc')
            ->add('abo_top_nrj')
            ->add('desabo_top_nrj')
            ->add('inst_top_nrj')
            ->add('abo_zen')
            ->add('desabo_zen')
            ->add('inst_zen')
            ->add('abo_bien_etre')
            ->add('desabo_bien_etre')
            ->add('inst_bien_etre')
            ->add('abo_wellness')
            ->add('desabo_wellness')
            ->add('inst_wellness')
            ->add('abo_detente')
            ->add('desabo_detente')
            ->add('inst_detente')
            ->add('abo_liberte')
            ->add('desabo_liberte')
            ->add('inst_liberte')
            ->add('abo_liberte_hc')
            ->add('desabo_liberte_hc')
            ->add('inst_liberte_hc')
            ->add('abo_liberte_plus')
            ->add('desabo_liberte_plus')
            ->add('inst_liberte_plus')
            ->add('abo_liberte_journee')
            ->add('desabo_liberte_journee')
            ->add('inst_liberte_journee')
            ->add('abo_matin')
            ->add('desabo_matin')
            ->add('inst_matin')
            ->add('abo_junior')
            ->add('desabo_junior')
            ->add('inst_junior')
            ->add('abo_senior')
            ->add('desabo_senior')
            ->add('inst_senior')
            ->add('abo_fitness_plus')
            ->add('desabo_fitness_plus')
            ->add('inst_fitness_plus')
            ->add('abo_partenaire')
            ->add('desabo_partenaire')
            ->add('inst_partenaire')
            ->add('abo_sqbb')
            ->add('desabo_sqbb')
            ->add('inst_sqbb')
            ->add('abo_gold')
            ->add('desabo_gold')
            ->add('inst_gold')
            ->add('abo_bouge_tes_formes')
            ->add('desabo_bouge_tes_formes')
            ->add('inst_bouge_tes_formes')
            ->add('abo_option_bienetre_plus_fitness')
            ->add('desabo_option_bienetre_plus_fitness')
            ->add('inst_option_bienetre_plus_fitness')
            ->add('abo_option_aquagym')
            ->add('desabo_option_aquagym')
            ->add('inst_option_aquagym')
            ->add('abo_option_aquafitness')
            ->add('desabo_option_aquafitness')
            ->add('inst_option_aquafitness')
            ->add('abo_seconde_option')
            ->add('desabo_seconde_option')
            ->add('inst_seconde_option')
            ->add('total_abo')
            ->add('total_desabo')
            ->add('inst_total')
            ->add('taux_desabo')
            ->add('notes')
            ->add('enregistrer', SubmitType::class, [
                'attr' => ['class' => 'bg-danger text-white w-50 mt-3 mb-5'],
                'row_attr' => ['class' => 'text-center']
            ]);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pass::class,
        ]);
    }
}
